services:
  dev-container:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    volumes:
      - ./workspace:/workspace
      - ./setup:/setup
    env_file:
      - .env
    tty: true
    ports:
      - "8000:8000"  # FastAPI
      - "5173:5173"  # Vite-React
      - "5432:5432"  # PostgreSQL
      - "8080:8080"  # Airflow
      - "5000:5000"  # Extra