services:
  dev-container:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    volumes:
      - ./workspace:/workspace
      - ./setup:/setup
    env_file:
      - .env
    tty: true
